apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mavendemo
  name: mavendemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavendemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mavendemo
    spec:
      containers:
      - image: docker.io/conmeobeou1253/mavendemo
        name: mavendemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mavendemo
  name: mavendemo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mavendemo
  type: LoadBalancer
status:
  loadBalancer: {}
---
